name: BuildFully
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'zulu' # See 'Supported distributions' for available options
            java-version: '21'
        - name: 克隆 Wenkrangha/BoatFly 公共存储库
          uses: GuillaumeFalourd/clone-github-repo-action@v2.1
          with:
            depth: 1
            branch: 'master'
            owner: 'Wenkrangha' 
            #请更改用户为你的用户名
            repository: 'BoatFly'
        - name: 编译 BoatFly 本体
          run: mvn package -q
        - name: 克隆 Wenkrangha/BoatFly-BootLoader 公共存储库
          uses: GuillaumeFalourd/clone-github-repo-action@v2.1
          with:
            depth: 1
            branch: 'master'
            #请更改用户为你的用户名
            owner: 'Wenkrangha'
            repository: 'BoatFly-Bootloader'
        - name: 准备资源文件以开始编译 BoatFly-Bootloader    
          run: |
             cp target/BoatFly-*.jar ./BoatFly-Bootloader/src/main/resources/
             rm -rf /target
        - name: 编译 BoatFly-BootLoader 启动器 
          run: |
            cd BoatFly-Bootloader
            mvn package -q
        - uses: actions/upload-artifact@v1
          with:
            name: BoatFly-Fully
            path: BoatFly-Bootloader/target/BoatFly-BootLoader-1.0.jar
