name: BuildFully
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'zulu' # See 'Supported distributions' for available options
            java-version: '21'
        - name: Clone Wenkrangha/BoatFly PUBLIC repository
          uses: GuillaumeFalourd/clone-github-repo-action@v2.1
          with:
            depth: 1
            branch: 'master'
            owner: 'Wenkrangha'
            repository: 'BoatFly'
        - run: cd BoatFly
        - name: Build BoatFly
          run: mvn package
        - run: cd ..
        - name: Clone Wenkrangha/BoatFly-BootLoader PUBLIC repository
          uses: GuillaumeFalourd/clone-github-repo-action@v2.1
          with:
            depth: 1
            branch: 'master'
            owner: 'Wenkrangha'
            repository: 'BoatFly-Bootloader'
        - run: cd ./BoatFly    
        - run: version=`awk '/<version>[^<]+<\/version>/{gsub(/<version>|<\/version>/,"",$1);print $1;exit;}' pom.xml`   
        - run: cd ..
        - run: cp ./BoatFly/target/BoatFly-$version ./BoatFly-BootLoader/src/main/resources/
        - run: cd BoatFly-Bootloader
        - name: Build BoatFly BootLoader
          run: mvn package
        - uses: actions/upload-artifact@v1
          with:
            name: BoatFly-Fully
            path: ${{ github.workspace }}/BoatFly/target/BoatFly-$version

